export enum SafeKeyAsset
{
    FontCreanBeige  = "FontCreanBeige",
    ModelBlade = "ModelBlade",
    ModelGrass = "ModelGrass",
    ModelFlower = "ModelFlower",
    TexureBlade = "TexureBlade",
    IMGButtonPlay = "IMGButtonPlay",
    IMGBUttonSetting = "IMGButtonSetting",
    IMGBackGroundSetting = "BackgroundSetting",
    IMGButtonCLose = "IMGButtonCLose",
    IMGButtonSoundBG = "IMGButtonSoundBG",
    IMGButtonSoundSFX = "IMGButtonSoundSFX",
    IMGTitleSetting = "IMGTitleSetting",
    IMGIconWin = "IMGIconWin",
    IMGIConLose = "IMGIConLose",
    IMGBtnPlayAgain = "IMGBtnPlayAgain",
    IMGBackToMenU = "IMGBackToMenU",
    IMGRevive = "IMGRevive",
    IMGBtnCloseSoundBG = "IMGBtnCloseSoundBG",
    IMGBtnCloseSoundSFX = "IMGBtnCloseSoundSFX",
    ModelStar = "ModelStar",
    IMGIconPowerUp = "IMGIconPowerUp",
    IMGFlowerTexure = "IMGFlowerTexure",
    ModelParticleGrass = "ModelParticleGrass",
    TextureBackgroundWate = "TextureBackgroundWate",
    ModelParticleLose = "ModelParticleLose",
}